apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: webhook-secret-store
spec:
  provider:
    webhook:
      method: POST
      url: "http://server:5000/api/secrets"
      result:
        jsonPath: "$.secret"
      headers:
        Content-Type: application/json
      body: '{ "key": "{{ .remoteRef.key }}" }'